### ISSUE TITLE
Allow newer python-magic versions

### ISSUE THREAD

**Issue by darix** [mautrix/python#125]
```
"detect_mimetype": ["python-magic>=0.4.15,<0.5"],
```

is this still required? This blocks distributions to move the whole stack forward.

**Comment by tulir** [comment]
The latest version of python-magic is 0.4.27.

Anyway, version caps are there for safety, they're not required and also not enforced at runtime. Distributions are free to ignore them, but then things may break if the package makes a breaking change.
