### ISSUE TITLE
Create bridge for revolt

### ISSUE THREAD

**Issue by itsnotsaved** [mautrix/python#55]
This is a request for create a bridge for revolt (https://revolt.chat). https://github.com/revoltchat Just a privacy friendly solution to discord. Some docs https://developers.revolt.chat/api/

It's already a popular service https://revolt.social/

Past you discontinued support for keybase then i think you have time to invest for this.

soon! soON!

@tulir @Half-Shot @sumnerevans

**Comment by sumnerevans** [comment]
This is not the appropriate place to ask for developers to create a bridge.

**Comment by itsnotsaved** [comment]
> This is not the appropriate place to ask for developers to create a bridge.

sorry, so where?
