### ISSUE TITLE
Maybe missing EventType or alternative for threaded response?

### ISSUE THREAD

**Issue by flancian** [mautrix/python#88]
Hi there! Thank you for writing mautrix and maubot, they are awesome :)

I was digging around and found no obvious way of responding to messages in a thread (which is admittedly pretty new functionality in Element, only being available in https://develop.element.io). I found https://github.com/mautrix/python/blob/46e8ef309da152effb050ba4aafd9d5841572a2c/mautrix/types/event/type.py#L187 with all types; do you know if this is missing a new message type or there is some other way of communicating threading intent to the supporting clients?

Thank you!

**Comment by tulir** [comment]
Threads go in `m.relates_to`, custom relation types are already allowed

```python
THREAD = RelationType("io.element.thread")
...
content = TextMessageEventContent(..., relates_to=RelatesTo(rel_type=THREAD, event_id=...))
await client.send_message(room_id, content)
```

**Comment by flancian** [comment]
Thank you for the pointer! This and the great example in https://github.com/maubot/echo/blob/master/echo.py (for the imports) got me going:

https://github.com/flancian/agora-bot-matrix/commit/37ce433ceb0909f6f27da6897afe9e77e43ee900

Have a great evening!
