### ISSUE TITLE
Publicly export symbols for Pyright

### ISSUE THREAD

**Issue by vegaelle** [mautrix/python#90]
[Pyright’s documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface) on symbol exporting mentions that imports in the form `from .A import B` in an `__init__.py` file considers that `A` isn’t private but `B` is. The documentation suggest either using a `__all__` attribute in the `__init__.py` or import symbols with aliases (like `from A import B as B`).

Currently, Pyright will complain about a `from mautrix.types import UserID` for example, saining that `"UserID" is not exported from module "mautrix.types". Import "from mautrix.types.primitive" instead`.

Would it be possible to add such explicitly public imports in Mautrix?

**Comment by tulir** [comment]
That sounds absolutely horrible and completely wrong, but I guess pyright is common enough that it should be supported

**Comment by tulir** [comment]
https://github.com/mautrix/python/commit/e1453f94fd8fbaf32284e9f149f318fff379d5ef
